### PR TITLE
Update Rf09

### PR DESCRIPTION
**Pull request by tmieslinger**

### CODE REVIEW

**Comment by lvol08** [comment]
I just had a look on the changes and the report and I think it looks pretty good in general. There are just two things, that I was wondering about:

1. Regarding HALO_0205_sl1, one could maybe implement the number of good dropsondes. I saw it in another report (RF10), so it might be good to do it equally.

2. Maybe circle 4 could be started 1s later, so one would have the start of the circle 60s before the first sonde got launched and as far as I can see, it would not change anything else except that the phase before the circle would be a second longer or is there another reason, why the starting point was chosen like this?

**Comment by tmieslinger** [comment]
Thanks Lea for the review!
I changed the circle 4 / circling 2 start time just as you suggested. 
Adding the dropsonde number in flight segments other than circles is a good point. We should discuss that in the mattermost channel and probably combine it with the general rewriting of good dropsondes in the next days.

Thanks again :)

**Comment by marc-prange** [comment]
Is this ready for merging? Additional changes may be made via a new PR.

**Comment by tmieslinger** [comment]
@Smpljack I suggest to merge it! I updated RF09 such that it includes the latest dropsonde definitions and still keeps the criteria concerning the `circle` starts 60 sec prior to the first sonde. The maximum shift in circle start time was 9sec compared to the old dropsonde definition.

**Pull request merged**
