### PR TITLE
Updated rf14

### PR DESCRIPTION
**Pull request by marc-prange**

### CODE REVIEW

**Review by tmieslinger — COMMENTED** [review]
Hi Marc, 

Thanks for working through this slightly complicated flight! 
I have a few suggestions without becoming to precise as the times might shift slightly as soon as you include the new dropsonde definition anyway.

* `circle 2` is incomplete anyway, so why not put the circle break 1 completely into circle 2?
* `circle 3` probably mention the change in flight leven in the irregularities statement? And probably also that the circle is not fully closed?
* why not include the 15 seconds of `circle break 3` within `circle 6`?
* mention altitude change at the end of `circle 6` in the irregularities statement?
*'cricling 3'  includes the circle deviation that is explicitly excluded from `cricle break 2`. This seems slightly inconsistent. I suppose your respective irregularities statement got mixed with another statement. Check line 161 again. 

The full flight looks a bit like a "Binokel" :)

**Comment by TheresaLang** [comment]
Hi Marc,
it looks perfect now! I only have two tiny suggestions, but I think you should decide whether to include them or not.
1) There are irregularities stating that the altitude of the aircraft changed for circle 1 and circle 3. Should there then also be irregularities for circle 4 and circle 6 for consistency?
2) As circle 3 is the one at NTAS, maybe you could include that in the name (e.g. "circle 3 at NTAS"), such that it is directly visible that this is not a "usual" circle.

**Comment by TheresaLang** [comment]
Oh and I just saw that there are two ``platform`` attributes in the file

**Comment by d70-t** [comment]
This PR includes many changes which are unrelated to RF14 but cover changes in the various python utilities. I suggest to remove the changes in the Python files from this PR and if they are not yet part of `master`, put them into a separate PR.

**Comment by marc-prange** [comment]
> This PR includes many changes which are unrelated to RF14 but cover changes in the various python utilities. I suggest to remove the changes in the Python files from this PR and if they are not yet part of `master`, put them into a separate PR.

Good point, I wasn't sure how to deal with this, because I needed to update these functions in this branch to update the flight, but the functions are obviously not relevant for the change this branch is trying to commit. Now I simply reverted the commit, but is there a better way to handle such an issue? Should I first rebase the branch on my origin/master and then this PR would only show what I changed compared to the origin/master, which would only be the RF14 file yaml file?

Thanks Tobi!

**Pull request merged**
