### PR TITLE
update HALO-0124 to all new defs

### PR DESCRIPTION
**Pull request by Geet-George**
Update HALO-0124 (RF03) to:
- new segment definitions
- segment IDs
- kinds
- contact tags

### CODE REVIEW

**Comment by marc-prange** [comment]
Ready for merging?

**Comment by Geet-George** [comment]
I think so... For RF03, as in RF04, I have stuck to the definition of least difference in heading between start and end. That should be the only point of conflict. Everything else should be okay and ready to merge.

**Comment by Geet-George** [comment]
Wait.. I need to add underscores in the segment_ids. Gimme 10 minutes, and then, it'll be ready to merge.

**Comment by Geet-George** [comment]
RF03 is ready to merge.

**Comment by d70-t** [comment]
I put my comments into another PR on Geets branch. I am wondering if that works well: Geet-George/halo-flight-phase-separation#3

**Comment by Geet-George** [comment]
I guess it does.. I merged your PR. :)

**Comment by Geet-George** [comment]
This PR is ready to merge.

Tobi, should we check the late/early sondes attribution to circles for all flights? This would create less confusion later.

**Pull request merged**
